import { defineMessages } from '@edx/frontend-platform/i18n';

const messages = defineMessages({
  titleStudio: {
    id: 'instructor.toolbar.studio',
    defaultMessage: 'Studio',
    description: 'Button to view in studio',
  },
  filterTitle: { id: 'learningpath.filter.title', defaultMessage: 'Filter' },
  clearAll: { id: 'learningpath.filter.clear_all', defaultMessage: 'Clear all' },
  closeFilterAlt: { id: 'learningpath.filter.close_alt', defaultMessage: 'Close filter' },
  myInvitations: { id: 'learningpath.filter.my_invitations', defaultMessage: 'My Invitations' },
  accepted: { id: 'learningpath.filter.accepted', defaultMessage: 'Accepted' },
  sent: { id: 'learningpath.filter.sent', defaultMessage: 'Sent' },
  selfEnrollment: { id: 'learningpath.filter.self_enrollment', defaultMessage: 'Self Enrollment' },
  catalogStatus: { id: 'learningpath.filter.catalog_status', defaultMessage: 'Catalog Status' },
  openStatus: { id: 'learningpath.filter.open', defaultMessage: 'Open' },
  upcomingStatus: { id: 'learningpath.filter.upcoming', defaultMessage: 'Upcoming' },
  endedStatus: { id: 'learningpath.filter.ended', defaultMessage: 'Ended' },
  partnerLabel: { id: 'learningpath.filter.partner', defaultMessage: 'Partner' },
  apply: { id: 'learningpath.filter.apply', defaultMessage: 'Apply' },

  failedToLoadDetail: { id: 'learningpath.detail.failed_to_load', defaultMessage: 'Failed to load detail' },
  backToMyCatalogs: { id: 'learningpath.detail.back_to_my_catalogs', defaultMessage: 'Back to My Catalogs' },
  learningPathLabel: { id: 'learningpath.detail.learning_path_label', defaultMessage: 'Learning Path:' },
  enrolling: { id: 'learningpath.detail.enrolling', defaultMessage: 'Enrolling...' },
  enrolled: { id: 'learningpath.detail.enrolled', defaultMessage: 'Enrolled' },
  acceptInvitationText: { id: 'learningpath.detail.accept_invitation', defaultMessage: 'Accept the invitation' },
  noSubCourses: { id: 'learningpath.detail.no_sub_courses', defaultMessage: 'No sub-courses found in this learning path.' },
  accessEnds: { id: 'learningpath.detail.access_ends', defaultMessage: 'Access ends' },
  certificate: { id: 'learningpath.detail.certificate', defaultMessage: 'Certificate' },
  coursesIncludeCertification: { id: 'learningpath.detail.courses_include_certification', defaultMessage: 'Courses include certification' },
  coursesCount: { id: 'learningpath.detail.courses_count', defaultMessage: '{count} courses' },
  accessStartsOnPrefix: { id: 'learningpath.card.access_starts_on_prefix', defaultMessage: 'Access starts on' },
  accessEndedOnPrefix: { id: 'learningpath.card.access_ended_on_prefix', defaultMessage: 'Access ended on' },
  accessUntilPrefix: { id: 'learningpath.card.access_until_prefix', defaultMessage: 'Access until' },
  catalogManager: { id: 'learningpath.card.catalog_manager', defaultMessage: 'Catalog Manager' },
  manage: { id: 'learningpath.card.manage', defaultMessage: 'Manage' },
  viewCatalogInfo: { id: 'learningpath.card.view_catalog_info', defaultMessage: 'View Catalog Info' },
  goToCatalog: { id: 'learningpath.card.go_to_catalog', defaultMessage: 'Go to the catalog' },
  acceptInvitationBtn: { id: 'learningpath.card.accept_invitation_btn', defaultMessage: 'Accept Invitation' },
  view: { id: 'learningpath.card.view', defaultMessage: 'View' },

  myCatalogs: { id: 'learningpath.dashboard.my_catalogs', defaultMessage: 'My Catalogs' },
  searchPlaceholder: { id: 'learningpath.dashboard.search_placeholder', defaultMessage: 'Search' },
  searchAlt: { id: 'learningpath.dashboard.search_alt', defaultMessage: 'Search' },
  filterButton: { id: 'learningpath.dashboard.filter_button', defaultMessage: 'Filter' },
  showing: { id: 'learningpath.dashboard.showing', defaultMessage: 'Showing {showing} of {total}' },
  noMatchingResults: { id: 'learningpath.dashboard.no_matching_results', defaultMessage: 'No matching results' },
  tryAnotherSearch: { id: 'learningpath.dashboard.try_another_search', defaultMessage: 'Try another search or clear your filters' },
  noResultsAlt: { id: 'learningpath.dashboard.no_results_alt', defaultMessage: 'No results' },

  moreDetails: { id: 'learningpath.course.more_details', defaultMessage: 'More Details' },
  startCourse: { id: 'learningpath.course.start_course', defaultMessage: 'Start Course' },
  viewCertificate: { id: 'learningpath.course.view_certificate', defaultMessage: 'View Certificate' },
  continueText: { id: 'learningpath.course.continue', defaultMessage: 'Continue' },
  loadingText: { id: 'learningpath.course.loading', defaultMessage: 'Loading...' },
  enrolledCount: { id: 'learningpath.course.enrolled_count', defaultMessage: '{count} Enrolled' },
  hoursText: { id: 'learningpath.course.hours', defaultMessage: '{hours} Hours' },
  startsOn: { id: 'learningpath.course.starts_on', defaultMessage: 'Starts {date}' },
  goBack: { id: 'learningpath.course.go_back', defaultMessage: 'Go Back' },
  courseChip: { id: 'learningpath.course.course_chip', defaultMessage: 'COURSE' },
  noDescription: { id: 'learningpath.course.no_description', defaultMessage: 'No description available.' },
  earnCertificate: { id: 'learningpath.course.earn_certificate', defaultMessage: 'Earn a certificate' },
  approxDuration: { id: 'learningpath.course.approx_duration', defaultMessage: 'Approx. duration' },
  maxEnrolledUsers: { id: 'learningpath.course.max_enrolled_users', defaultMessage: 'User enrollment limit' },
  users: { id: 'learningpath.course.users', defaultMessage: '{count} users' },
  instructorPaced: { id: 'learningpath.course.instructor_paced', defaultMessage: 'Instructor-paced' },
  progressAtYourOwnSpeed: { id: 'learningpath.course.progress_at_your_own_speed', defaultMessage: 'Progress at your own speed' },
  followCourseSchedule: { id: 'learningpath.course.follow_course_schedule', defaultMessage: 'Follow the course schedule' },
  errorLoadingCourse: { id: 'learningpath.course.error_loading', defaultMessage: 'Error loading course' },
  returnToDashboard: { id: 'learningpath.course.return_to_dashboard', defaultMessage: 'Return to dashboard' },
  courseNotFound: { id: 'learningpath.course.not_found', defaultMessage: 'Course not found' },
  couldNotFindCourse: { id: 'learningpath.course.could_not_find', defaultMessage: "We couldn't find the requested course." },

  dataSharingTitle: { id: 'learningpath.data_sharing.title', defaultMessage: 'Data Sharing Authorization' },
  dataSharingDescription: { id: 'learningpath.data_sharing.description', defaultMessage: 'To enroll in this course through the {partnerName} catalog, we need your permission to share certain information about your activity in this course with {partnerName}. This information will be used solely for tracking and reporting purposes within their training program.' },
  dataSharingByAllowing: { id: 'learningpath.data_sharing.by_allowing', defaultMessage: 'By allowing data sharing, you confirm that:' },
  dataSharingLi1: { id: 'learningpath.data_sharing.li1', defaultMessage: 'You have been invited or your email is eligible for this corporate catalog.' },
  dataSharingLi2: { id: 'learningpath.data_sharing.li2', defaultMessage: 'You understand that the shared information includes data such as your course progress, grades, and completion status.' },
  dataSharingLi3: { id: 'learningpath.data_sharing.li3', defaultMessage: 'You consent to {partnerName} receiving this information in accordance with applicable data protection laws (GDPR).' },
  dataSharingConfirm: { id: 'learningpath.data_sharing.confirm', defaultMessage: 'Do you authorize sharing your data for this course with {partnerName}?' },
  dataSharingDoNotShare: { id: 'learningpath.data_sharing.do_not_share', defaultMessage: 'Do Not Share' },
  dataSharingAllowAndContinue: { id: 'learningpath.data_sharing.allow_and_continue', defaultMessage: 'Allow and Continue' },
  // Additional messages used across learningpath components
  activateAccountAlert: { id: 'learningpath.dashboard.activate_account', defaultMessage: 'Activate your account! Check your inbox for an account activation link from {siteName}.' },
  activateAccountHelp: { id: 'learningpath.dashboard.activate_account_help', defaultMessage: 'If you need help, {contactLink}.' },
  enterpriseDashboardAccess: { id: 'learningpath.dashboard.enterprise_access', defaultMessage: 'You have access to the {label} dashboard. To access the courses available to you through {label}, visit the {linkText}.' },
  enterpriseDashboardLinkText: { id: 'learningpath.dashboard.enterprise_link_text', defaultMessage: '{label} dashboard' },
  contactUs: { id: 'learningpath.common.contact_us', defaultMessage: 'contact us' },
  partnerLogoAlt: { id: 'learningpath.card.partner_logo_alt', defaultMessage: 'Partner logo' },
  coursesTitle: { id: 'learningpath.courses.title', defaultMessage: 'Courses' },
  noEndDate: { id: 'learningpath.detail.no_end_date', defaultMessage: 'No end date' },
  enrollmentEndDate: { id: 'learningpath.detail.enrollment_end_date', defaultMessage: 'Enrollment end date' },
  progressCompleted: { id: 'learningpath.progress.completed', defaultMessage: 'Completed' },
  progressAccepted: { id: 'learningpath.progress.accepted', defaultMessage: 'Accepted' },
  progressSent: { id: 'learningpath.progress.sent', defaultMessage: 'Sent' },
  progressStatusAria: { id: 'learningpath.progress.aria', defaultMessage: 'Progress status: {status}' },
  pendingInvitation: { id: 'learningpath.status.pending_invitation', defaultMessage: 'Pending Invitation' },
  activeStatus: { id: 'learningpath.status.active', defaultMessage: 'Active' },
});

export default messages;
